@useRestClient
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json


{
  "name": "Binh nguyen",
  "email": "binhnguyen@gmail.com",
  "password": "binhnguyen"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "doantran@gmail.com",
  "password": "doantran"
}

// Search User
###
GET http://localhost:5000/api/user/search/user?q=doan

// Lấy thông tin của user
###
GET http://localhost:5000/api/user/6400b87b00ff1fe387cbb4e3
// API update thông tin user
###
PUT http://localhost:5000/api/user/update/user
Content-Type: application/json

{
  "phone": "068967890"
}

// Gửi yêu cầu kết bạn: POST http://localhost:5000/api/user/friend-requests/:recipientId
###
POST http://localhost:5000/api/user/friend-requests/6400b87b00ff1fe387cbb4e3

// Danh sách lời mời kết bạn
###
GET http://localhost:5000/api/user/friend-requests/list

// phản hồi yêu cầu kết bạn: http://localhost:5000/api/user/:requestId
###
PUT http://localhost:5000/api/user/640bd7ea1a0d67b9dcbed050
Content-Type: application/json

{
  "status": "accepted"
}

// Lấy danh sách bạn bè
###
GET http://localhost:5000/api/user/friends/6405e1f56f63dc3d316787e2
// Lấy danh sách gợi ý bạn bè
###
GET http://localhost:5000/api/user/friends-suggestions/list
// Lấy danh sách bài post của bạn bè: http://localhost:5000/api/user/postFromFriends/:userId
###
GET http://localhost:5000/api/user/postFromFriends/list

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Cookie: "access_token"=""

{
  "content": "Đây là bài post thứ nhất của Lan Nguyễn"
}
// API like Post
###
POST http://localhost:5000/api/posts/likes/6405e2e46f63dc3d316787ea
// API unlike Post
###
DELETE http://localhost:5000/api/posts/unlikes/6405e2e46f63dc3d316787ea
// API share post
###
POST http://localhost:5000/api/posts/shares/6405e2196f63dc3d316787e4
# Update post
###
PUT http://localhost:5000/api/posts/6405e2196f63dc3d316787e4
Content-Type: application/json

{
  "content": "Đây là bài post thứ 2 của Đoan Trần ......"
}

###
GET http://localhost:5000/api/posts

###
GET http://localhost:5000/api/posts/6404a9d1583c6dcffb06ae8b

###
POST http://localhost:5000/api/comment/6405e2196f63dc3d316787e4
Content-Type: application/json

{
  "content": "Bình luận thứ hai"
}
// API lấy ra comment của bài post
###
GET http://localhost:5000/api/comment/6405e2196f63dc3d316787e4

# Repcomment
###
POST http://localhost:5000/api/comment/6405e2196f63dc3d316787e4/6405ec4326108a72adcabe92
Content-Type: application/json

{
  "content": "RepComment thứ ba"
}
###
PUT http://localhost:5000/api/comment/6405e2196f63dc3d316787e4/6405ec4326108a72adcabe92/
Content-Type: application/json

{
  "content": "Chỉnh sửa comment thứ nhất"
}


###
PUT http://localhost:5000/api/comment/6405e2196f63dc3d316787e4/6405ec4326108a72adcabe92/6406029bc5f9e2a389498bbe
Content-Type: application/json

{
  "content": "Chỉnh sửa repcomment thứ hai nè"
}

// API chức năng lưu bài viết
###
POST http://localhost:5000/api/user/saved/de-xem-sau/6405e2196f63dc3d316787e4
// API lấy ra những bài viết đã lưu
###
GET http://localhost:5000/api/user/getSaved/saved-posts?key=de-xem-sau&page=1&limit=10
// 
###
GET http://localhost:5000/api/user/getSaved/getSavedIds

// ======== Chat =========

// API create chat
###
POST http://localhost:5000/api/chat/messages
Content-Type: application/json

{
  "receiverId": "6405e1f56f63dc3d316787e2",
  "content": "Chào"
}
// API getChatMessages
###
GET http://localhost:5000/api/chat/messages/6400b87b00ff1fe387cbb4e3/6405e1f56f63dc3d316787e2 
// API getChatContacts: API lấy danh sách người dùng đã chat với người dùng hiện tại
###
GET http://localhost:5000/api/chat/messages/getChatContacts
  
// getFriendBirthdayToday
###
GET http://localhost:5000/api/user/friends/birthday/today
// getFriendBirthdayByMonth
###
GET http://localhost:5000/api/user/friends/birthday/2